version: '3.8'

services:
  prestashop:
    container_name: BE_196638_prestashop
    restart: unless-stopped
    image: kuprraman/be_196638:latest
    depends_on:
      - admin-mysql_db
    ports:
      - 19663:443
    volumes:
      - ps_img:/var/www/html/img
      - BE_196638_ps_config:/var/www/html/app/config
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_196638
      DB_USER: root
      DB_PASSWD: student
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - prestashop_network
      - admin-mysql_default

networks:
    prestashop_network:
    admin-mysql_default:
        external: true

volumes:
  ps_img:
  BE_196638_ps_config: